title: Romsey Chamber of Commerce and Industry
description: Supporting business and the community in the Romsey area
sitename: 'http://www.romseychamber.co.uk/'
cloudinary: 'http://res.cloudinary.com/romsey-chamber'
page_size: 7
contact:
  telephone: 01794 513135
  email: 'info@romseychamber.co.uk'
  address1: 18 Market Place
  city: Romsey
  county: Hampshire
  country: UK
  postcode: SO51 8NA
  facebook: 'https://www.facebook.com/pages/Romsey-Chamber-of-Commerce-and-Industry/343650312503091'
  twitter: '@RomChamb'


################################################################
################################################################
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  events:
    output: true
  members:
    output: false
  news:
    output: true
  offers:
    output: false
  resources:
    output: false
defaults:
  -
    scope:
      path: ''
      type: news
    values:
      layout: article
  -
    scope:
      path: ''
      type: events
    values:
      layout: event
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
prose:
  ignore:
    - _includes
    - _layouts
    - assets
    - pages
    - .gitignore
    - CNAME
    - Gemfile
    - favicon.ico
  metadata:
    _events:
      - name: title
        field:
          element: text
          label: Title
      - name: date
        field:
          element: text
          label: Date
          help: 'yyyy-mm-dd'
      - name: end-date
        field:
          element: text
          label: End Date
          help: 'yyyy-mm-dd'
      - name: start-time
        field:
          element: select
          label: Start Time
          options:
            - value: ''
            - value: '00:00'
            - value: '00:15'
            - value: '00:30'
            - value: '00:45'
            - value: '01:00'
            - value: '01:15'
            - value: '01:30'
            - value: '01:45'
            - value: '02:00'
            - value: '02:15'
            - value: '02:30'
            - value: '02:45'
            - value: '03:00'
            - value: '03:15'
            - value: '03:30'
            - value: '03:45'
            - value: '04:00'
            - value: '04:15'
            - value: '04:30'
            - value: '04:45'
            - value: '05:00'
            - value: '05:15'
            - value: '05:30'
            - value: '05:45'
            - value: '06:00'
            - value: '06:15'
            - value: '06:30'
            - value: '06:45'
            - value: '07:00'
            - value: '07:15'
            - value: '07:30'
            - value: '07:45'
            - value: '08:00'
            - value: '08:15'
            - value: '08:30'
            - value: '08:45'
            - value: '09:00'
            - value: '09:15'
            - value: '09:30'
            - value: '09:45'
            - value: '10:00'
            - value: '10:15'
            - value: '10:30'
            - value: '10:45'
            - value: '11:00'
            - value: '11:15'
            - value: '11:30'
            - value: '11:45'
            - value: '12:00'
            - value: '12:15'
            - value: '12:30'
            - value: '12:45'
            - value: '13:00'
            - value: '13:15'
            - value: '13:30'
            - value: '13:45'
            - value: '14:00'
            - value: '14:15'
            - value: '14:30'
            - value: '14:45'
            - value: '15:00'
            - value: '15:15'
            - value: '15:30'
            - value: '15:45'
            - value: '16:00'
            - value: '16:15'
            - value: '16:30'
            - value: '16:45'
            - value: '17:00'
            - value: '17:15'
            - value: '17:30'
            - value: '17:45'
            - value: '18:00'
            - value: '18:15'
            - value: '18:30'
            - value: '18:45'
            - value: '19:00'
            - value: '19:15'
            - value: '19:30'
            - value: '19:45'
            - value: '20:00'
            - value: '20:15'
            - value: '20:30'
            - value: '20:45'
            - value: '21:00'
            - value: '21:15'
            - value: '21:30'
            - value: '21:45'
            - value: '22:00'
            - value: '22:15'
            - value: '22:30'
            - value: '22:45'
            - value: '23:00'
            - value: '23:15'
            - value: '23:30'
            - value: '23:45'
      - name: end-time
        field:
          element: select
          label: End Time
          options:
            - value: ''
            - value: '00:00'
            - value: '00:15'
            - value: '00:30'
            - value: '00:45'
            - value: '01:00'
            - value: '01:15'
            - value: '01:30'
            - value: '01:45'
            - value: '02:00'
            - value: '02:15'
            - value: '02:30'
            - value: '02:45'
            - value: '03:00'
            - value: '03:15'
            - value: '03:30'
            - value: '03:45'
            - value: '04:00'
            - value: '04:15'
            - value: '04:30'
            - value: '04:45'
            - value: '05:00'
            - value: '05:15'
            - value: '05:30'
            - value: '05:45'
            - value: '06:00'
            - value: '06:15'
            - value: '06:30'
            - value: '06:45'
            - value: '07:00'
            - value: '07:15'
            - value: '07:30'
            - value: '07:45'
            - value: '08:00'
            - value: '08:15'
            - value: '08:30'
            - value: '08:45'
            - value: '09:00'
            - value: '09:15'
            - value: '09:30'
            - value: '09:45'
            - value: '10:00'
            - value: '10:15'
            - value: '10:30'
            - value: '10:45'
            - value: '11:00'
            - value: '11:15'
            - value: '11:30'
            - value: '11:45'
            - value: '12:00'
            - value: '12:15'
            - value: '12:30'
            - value: '12:45'
            - value: '13:00'
            - value: '13:15'
            - value: '13:30'
            - value: '13:45'
            - value: '14:00'
            - value: '14:15'
            - value: '14:30'
            - value: '14:45'
            - value: '15:00'
            - value: '15:15'
            - value: '15:30'
            - value: '15:45'
            - value: '16:00'
            - value: '16:15'
            - value: '16:30'
            - value: '16:45'
            - value: '17:00'
            - value: '17:15'
            - value: '17:30'
            - value: '17:45'
            - value: '18:00'
            - value: '18:15'
            - value: '18:30'
            - value: '18:45'
            - value: '19:00'
            - value: '19:15'
            - value: '19:30'
            - value: '19:45'
            - value: '20:00'
            - value: '20:15'
            - value: '20:30'
            - value: '20:45'
            - value: '21:00'
            - value: '21:15'
            - value: '21:30'
            - value: '21:45'
            - value: '22:00'
            - value: '22:15'
            - value: '22:30'
            - value: '22:45'
            - value: '23:00'
            - value: '23:15'
            - value: '23:30'
            - value: '23:45'
      - name: image
        field:
          element: text
          label: Image
      - name: contact-name
        field:
          element: text
          label: Contact Name
      - name: email
        field:
          element: text
          label: Email
          value: 'info@romseychamber.co.uk'
      - name: telephone
        field:
          element: text
          label: Telephone
      - name: image
        field:
          element: text
          label: Image
      - name: website
        field:
          element: text
          label: Website
      - name: place
        field:
          element: select
          label: Place
          options:
            - name: Basepoint
              value: basepoint
            - name: Broadlands
              value: broadlands
            - name: Romsey Chamber Office
              value: chamber-office
            - name: Crosfield Hall
              value: crosfield-hall
            - name: "King John's House"
              value: king-johns-house
            - name: Plaza Theatre
              value: plaza-theatre
            - name: "Rum's Eg"
              value: rums-eg
            - name: The Abbey
              value: the-abbey
            - name: The Whitehorse
              value: the-whitehorse
            - name: Romsey Town Hall
              value: town-hall
      - name: address1
        field:
          element: text
          label: Address 1
      - name: address2
        field:
          element: text
          label: Address 2
      - name: city
        field:
          element: text
          label: City
      - name: county
        field:
          element: text
          label: County
      - name: country
        field:
          element: text
          label: Country
      - name: postcode
        field:
          element: text
          label: Postcode
    _members:
      - name: title
        field:
          element: text
          label: Title
      - name: category
        field:
          element: select
          label: Category
          options:
            - value: Business Services
            - value: Food
            - value: Healthcare
            - value: Leisure
            - value: Retail
            - value: Trades Services
      - name: image
        field:
          element: text
          label: Image
      - name: email
        field:
          element: text
          label: Email
      - name: telephone
        field:
          element: text
          label: Telephone
      - name: website
        field:
          element: text
          label: Website
      - name: facebook
        field:
          element: text
          label: Facebook URL
      - name: twitter
        field:
          element: text
          label: Twitter URL
      - name: address1
        field:
          element: text
          label: Address 1
      - name: address2
        field:
          element: text
          label: Address 2
      - name: city
        field:
          element: text
          label: City
          value: Romsey
      - name: county
        field:
          element: text
          label: County
          value: Hampshire
      - name: country
        field:
          element: text
          label: Country
          value: UK
      - name: postcode
        field:
          element: text
          label: Postcode
      - name: opening-hours
        field:
          element: multiselect
          label: Opening Hours
          alterable: True
          help: "Specification: http://schema.org/openingHours, e.g. 'Tu,Th 16:00-20:00' "
          options:
            - value: 'Mo-Tu 09:00-17:00'
            - value: 'We 09:00-19:00'
            - value: 'Th-Sa 09:00-17:00'
            - value: 'Mo-Fr 09:00-13:00'
            - value: 'Mo-Th 14:00-17:30'
            - value: 'Mo-Fr 09:30-16:30'
            - value: 'Sa 09:00-14:00'
            - value: 'Tu-Sa 10:00-16:00'
    _news:
      - name: title
        field:
          element: text
          label: Title
      - name: date
        field:
          element: text
          label: Date
          help: 'yyyy-mm-dd'
    _offers:
      - name: title
        field:
          element: text
          label: Title
      - name: member
        field:
          element: text
          label: Member
          help: Must match member's title exactly
    _resources:
      - name: title
        field:
          element: text
          label: Title
      - name: category
        field:
          element: select
          label: Category
          options:
            - value: Downloads
            - value: Websites
      - name: link
        field:
          element: text
          label: Website URL
      - name: download
        field:
          element: text
          label: Download File Name